### ISSUE TITLE
Put screenshots / pictures of screen in README

### ISSUE THREAD

**Issue by talentlessguy** [hsoft/collapseos#15]
It would be interesting to see screenshots of this OS even if it doesn't have GUI.
Photos of monitor with running OS may also be suitable

**Comment by QuercusFelis** [comment]
#20 Pull request created

**Comment by hsoft** [comment]
As I wrote in the PR, I don't think we need to widen the audience of Collapse OS to people who need screenshots of a shell. I'm a bit overwhelmed by how Collapse OS went viral, but it doesn't change the fact that it is targeted at a small audience by design.

**Comment by talentlessguy** [comment]
@hsoft why it is bad for this OS to be viral? Who is the target client (I thought every person)? Narrowing audience is not good IMO. I don't see anything bad in shell screenshots. It is just text, isn't it?

**Comment by hsoft** [comment]
Collapse OS' only goal is to program microcontrollers. It's because its scope is reduced that it can achieve its most important design goal of self-replicating on very very low specs. Unless you're in electronics, you don't need Collapse OS (well, nobody needs Collapse OS today :) ). It's true that at some point, if society effectively passes the point of collapse, we'll want this source code to be disseminated, so global recognition, for this, is good. But it's not ready yet. What it needs is development.

**Comment by talentlessguy** [comment]
@hsoft, that's a valid point. Maybe after some "stable" release it will be worth adding screenshots :)

**Comment by QuercusFelis** [comment]
I understand wanting to limit scope, but at least for the docs, visual demonstrations can be quite effective. Perhaps a screenshot of the shell for the shell portion of the docs may be of some use?

**Comment by schierlm** [comment]
Before adding screenshots, I'd rather add a link to a website that uses a [Javascript Z80 emulator](https://github.com/DrGoldfire/Z80.js) to run this project and experiment with it.

[Something like this](https://gist.githack.com/schierlm/96d84f0e98861f7d35965e3b91d8d31c/raw/11623fa62941e49f6854a25db6186499e7b84ccb/index.html)

(When building this minimal viable example, I noticed I could not add both ed and zasm sources to the same CFS, still being able to compile them, since both have a different file both called `io.asm`)

Of course, one could make that emulator much more user friendly, e.g. by adding support for a line-buffer (for copying texts to), support for typing non-printable-ascii characters (like the nullbyte in one of the examples), or loading/storing the SD card to disk image files or to local storage (currently it is lost when you close the page), or pasting/capturing console input/output, or supporting 2 sd cards at the same time, etc. etc.

But in the "desired" apocalyptic scenario you would not have this comfort, either :-P

[If you are interested in contributions like this, I could polish the code a bit and add more features]

**Comment by schierlm** [comment]
The web emulator is now available at https://schierlm.github.io/CollapseOS-Web-Emulator/ There are 3 different hardware combinations to emulate, and the default SD card also contains TinyBasic.

**Comment by hsoft** [comment]
@schierlm that's awesome! Adding a link to it in the README now.
