### ISSUE TITLE
Please make it CP/M compatible

### ISSUE THREAD

**Issue by jwatte** [hsoft/collapseos#43]
There are tons of CP/M software available on 8-inch floppy disks; anything from Wordstar to VisiCalc to Zork, as well as compilers for Pascal, FORTRAN, BASIC, and other important high-level languages.
This software could be run if you made the OS CP/M compatible.

(Then again, if you have a Z/80 you want to run an OS on, why wouldn't you just use CP/M directly?)

**Comment by keithstellyes** [comment]
On making it compatible: Sounds really hard, lol

On "why not just use CP/M?" CP/M makes a lot of assumptions about its overall system, doesn't it? You pretty much would have to bend the system around around CP/M, also can't easily make CP/M run on say, a TI.

**Comment by QuercusFelis** [comment]
CP/M compatibility is a long ways off and may not even be entirely feasible. With the design goals of this project, full compatibility is almost certainly impossible due to the unique requirements of individual programs, such as necessary peripherals or how they expect text or video output to function. I would consider it a monumental milestone to get even the simplest of CP/M programs running, let alone games, AutoCAD, or many of the available compilers. While both CP/M and CollapseOS are made for the z80, the rest of the actual machines they're designed to run on are wildly different. That said, it is not at all out of the question to port certain software from CP/M to CollapseOS.

**Comment by hsoft** [comment]
Collapse OS' only goal is to program microcontrollers with minimal complexity. Compatibility with CP/M would vastly increase its complexity while straying from its goal.

If Collapse OS is of any value to anyone having a different goal, I strongly encourage forking.
