### ISSUE TITLE
Múltiple archs?

### ISSUE THREAD

**Issue by piranna** [hsoft/collapseos#62]
If the purposse of the project is to use scavenged parte, you don't know what micro are you going to find, so probably instead of focusing just only on 8080/Z80 and derivates, we should get a more abstract framework that can be used on more architectures. This translate on focusing on documentation and tools, and later have code to init on diferent archs. The most common microcontrollers today un the homebrew scene would be ESP8266, but if we stick to popularity, probably the PIC16 family is the winner here.

Thoughts?

**Comment by f4grx** [comment]
PIC16 is an absolute pain to work with for general purpose applications. They are definitely usable for specific purpose projects, but I do not see a pic16 running an OS with an assembler and the capability to self-host.
Also related to the fact that they are hardware limited to ~4k of RAM and are unable to execute code from RAM.

I am currently working on a hc11 board.

STM32 and ARMs are another target, but they are not so easy to program.

**Comment by hsoft** [comment]
The OS is tied to the Z80, but the goal is to program any kind of popular microcontroller, including PIC. Therefore, it is on the roadmap to implement assemblers (and, if needed, programmers) for those microcontrollers, in z80 assembly.

**Comment by schierlm** [comment]
Also, there is a Z80 emulator for ESP8266, which manages it to provide the full 64KB of RAM to the Z80 (the ESP8266 has 96K of RAM). So making a recipe for this emulator (that treats the emulator itself a binary blob) might be feasible. On the other hand, most ESP8266 devices don't have any screen or input devices attached to it, since its default firmware can connect to Wifi networks. And if you can connect to a wifi network to talk to your ESP8266, you can probably run/emulate CollapseOS on the device you use for connecting to, or you won't need CollapseOS at all.

But it seems (no experience with it) that you can connect an I²C display or a PS/2 keyboard to it, so if you can also scavenge one of those 20x4 or 16x2 displays and find some ancient keyboards, you might create some nice and fast (80MHz should more than compensate for the emulation overhead) CollapseOS machine.

**Comment by piranna** [comment]
> But it seems (no experience with it) that you can connect an I²C display or a PS/2 keyboard to it, so if you can also scavenge one of those 20x4 or 16x2 displays and find some ancient keyboards, you might create some nice and fast (80MHz should more than compensate for the emulation overhead) CollapseOS machine.

My idea was more towards this, not use Wifi :-) But really, my proposal was that if we have scavenged a more powerful CPU, why not use it instead of use an emulator? By having docs about how to plug the display and the keyboard, it can be used both on the Z80 and the ESP8266, just only we would need to have docs for the devices and basic assembly code for boths... Not needed to be in the main repo, the main repo would be for the docs and later have subproyects for the assembly code of each architecture (CollapseOS/Z80, CollapseOS/ESP8266, CollapseOS/PIC16...).

If it would be possible to cross-compile the assembly code, that would be great :-D but maybe would make more sense to have the drivers in a generic form, AKA source code... Another alternative would be to have them in WebAssemble or LLVM-IR, that are in fact assembly code, and later compile/transpile it to the target architecture :-)

(Oh, and a WebAssembly target architecture would be great too :-P)

**Comment by hsoft** [comment]
> why not use it instead of use an emulator?

Because this OS is written in z80 assembly and is not portable.
