### ISSUE TITLE
zasm optimization: namespacing

### ISSUE THREAD

**Issue by hsoft** [hsoft/collapseos#76]
zasm's RAM usage is, in vast majority, composed of symbol names. Collapse OS already self-assembles with very little memory, but I'd like to bring the bar as low as possible.

An obvious road would be to shorten all labels in Collapse OS' code. However, because I think that significant names help readability a lot, I hesitate to do that. I had what I think is a good idea this morning: label namespacing. Example:

```
foo:
#baz:

bar:
#baz:

call foo#baz
call bar#baz
```

Labels in my code often have unit name prefixes for clarity and by changing those prefix into namespaces (a unit would have a top label with a prefix, and then all following labels would be prefixed with #) would help a lot.

Having a system like this would avoid having to repeat that prefix in the symbol table and thus reduce RAM usage. It would also reduce verbosity in labels.

**Comment by Clanmaster21** [comment]
To check I understand what you mean, for example at the start of all the string functions you'd have 
```
string:
#cmp:

#skip:

#len:
```
So that then the string functions can be called through `call string#function` ? It sounds like a good idea to me, it'd save RAM and not sacrifice readability. I feel like you could get away with shortening things like "Decimal" to "Dec", but I agree it isn't ideal. I was thinking of ways you could shorten symbols internally, one idea I had was to calculate some kind of hash from the symbol, but for an n bit hash the mean value of symbols before there's a clash would be 2^(n/2), so it'd be banking on luck heavily for any value of n small enough to be saving significant RAM. Whilst I think my idea is entirely useless, maybe shortenings like "Decimal" to "Dec" could be done internally?

**Comment by hsoft** [comment]
Yes, that's the idea.

I've also been toying with the idea of hashes, bumping in the same kind of roadblocks as you have.

**Comment by hsoft** [comment]
Thinking about it again, I'm not sure that it's such a good idea either. It only really work for "module" names and those modules's prefix are often short (3 chars). Adding one char for the `#`, that leaves only a gain of two chars per symbol. Still a gain, but a modest one.

Shortening names would yield better gains.

**Comment by hsoft** [comment]
Something that could yield interesting gains is a "prefix table". Each symbol has its prefix (first lower case word *or* word before underscore) put in a deduplicated table and each symbol refer to the beginning of its string with a prefix index. The table could have a maximum of 0xff entries and 0xff would mean "no prefix".

This would have the advantage of working for constants which can also be quite long.

**Comment by Clanmaster21** [comment]
That does sounds like it'd work, do you have any idea how many of the entries would get filled presently? And if there's more than 255 prefixes, would they just be picked in the order they appear during compiling?

**Comment by hsoft** [comment]
No, my RAM usage debugging with regards to zasm has been very hackish up until now. I've been planning on formalizing some kind of stderr interface for userspace and use this to make zasm spit useful stats (such as RAM usage).

**Comment by Clanmaster21** [comment]
Oh yeah, another idea I had was to place some limits on the characters used to define symbols, so lets say upper case letters + lower case letters + numbers + underscore or something (so 63 characters) and then each character would only need 6 bits instead of 8. Obviously that makes dealing with them much more painful, and I expect there'd be a pretty big performance hit as a result, but I thought it might be of interest anyway.
