### ISSUE TITLE
Asking more info about CFS filesystem

### ISSUE THREAD

**Issue by f4grx** [hsoft/collapseos#78]
Hello,
I would like to be able to read collapseOS volumes in my own sys11, so I need to understand your filesystem in depth.
It seems that the documentation is not fully explicit for a third party developer.

If I understand a file is a chain of 256-byte blocks, with 32 bytes metadata in the first block.

This is also the block size I was planning to use in my FS, which makes me happy.

But how are these blocks chained? Are they just contiguous?

So to enumerate files you just skip the announced number of blocks for a file?

I guessed this by reading the assembly but you should add more detailed info in the header of the file :)

Thanks!

FYI here is the documentation on my own planned filesystem, much more complex, no idea if I can achieve that in a 8k hc11 ROM https://github.com/f4grx/sys11/blob/master/monitor/RRSF.md

**Comment by hsoft** [comment]
There's really not much to say about CFS. It's brittle and under-designed, but its implementation is simple and could be whipped up quickly.

Yes, that's how blocks are linked: they're contiguous.

**Comment by f4grx** [comment]
OK, thanks, so it's a kind of first-fit non-volatile malloc, then. I understand.

Simplicity is the best for such a project, my own thing is probably too overengineered, because of my own embedded developer bias :p

**Comment by f4grx** [comment]
It would not be that hard to use the first two bytes of each page as a link pointer to support non-consecutive affectation and file growth. You could only store 254 bytes per "sector" but no one really cares.
If you have no time/interest for this I may develop it when I build my own Z80 board for collapseOS.

**Comment by gitjeff2** [comment]
Honestly, you probably want to consider a few things here:

1. Bit-rot.
2. Storage devices well past their "sell by" date.

You probably want to add some form of error correcting code. Back in the day, Compute! had an 8-bit efficient checksum algorithm baked into its [MLX software](https://en.wikipedia.org/wiki/MLX_(software)). It helped catch errors in type-in programs. For every 7 bytes of data, one byte is reserved for checksum data. That gets errors noticed, but won't help you fix them. Some codes exist, like [Hamming(7,4)](https://en.wikipedia.org/wiki/Hamming(7,4)) but aren't that efficient.

One compromise might look like this:

1. Checksum every N data bytes with an 1 checksum byte, pick an efficient interval.
2. Every byte of data loses one bit to parity.
3. Read operations verify checksum. This gives you the chance check parity to look for errors and sanity-check the checksum in case only the checksum block is bad.
4. This gives you enough information to reconstruct corrupt data quite a lot of the time. You'll have to unit test with intentional errors, but you get my point.
5. Whatever you cook-up for your data blocks in terms of parity and checksum you should do for your meta-data as well. The modern file system [Btrfs](https://en.wikipedia.org/wiki/Btrfs) does this.
6. Very critical metadata, such as the partition table, should be repeated more than once at regular intervals. The modern file system ext4 does this with its superblock.

I agree with @f4grx regarding treating sectors as linked-lists, this is how the [GEOS](https://en.wikipedia.org/wiki/GEOS_(8-bit_operating_system)) file system worked; [VLIR](http://unusedino.de/ec64/technical/formats/geos.html) was very database-like. But, that limits you to something like 16 MB files. You probably want some way to grow beyond this via some chunk of metadata that acts as a "glue" block and points to the start of the next linked list and more file data.

**Comment by f4grx** [comment]
Thanks for the info, I may use it for my own filesystem, even if it complicates a lot the IO routines (I'm just about to work on this now that I have a shell on my HC11).

For CollapseOS, given that the goal of this project is merely bootstrapping more complex computers, it may be too many features for @hsoft to consider.
