### ISSUE TITLE
Expr.asm reworking

### ISSUE THREAD

**Issue by Clanmaster21** [hsoft/collapseos#87]
I was looking through the code for expr.asm, and I think it could be simplified quite significantly. I'm still trying to get my head around it completely, one thing I'm confused about is how for example in 
`parseAddSubst` there's a bit like:
```
.found:
	ld	iy, _parseMultDiv
	call	_parseApply
```
So, does this mean if there's a + or -, it then checks if there's a \*, / or % immediately following it and applies it first? (I realise that's a simplification as _parseMultDiv calls _parseBitShift which calls _parseNumber, but still.) So for example, '10+ * 10' would be evaluated as (10*10)+10 = 110? 
My other question is, is this code running in ROM or RAM? It shouldn't make a huge difference either way, but it's best if I ask now just in case.
My idea is essentially to have two lists, one with a list of characters in the order of testing for them, and another for their corresponding apply functions, so like
```
list1:
.db	'*/+-', 0
list2:
.dw	.mult, .div, .plus, .minus, .none
```
And then the main loop of the code would be something like (in pseudo assembly):
```
mov bc, list1 - list2
mov list2-1, a	; place a at the end of the list as a sentinel
mov hl, list1
cpir	; finds a in list
sbc hl, bc ; hl is now list2 + 2*(however far through the list)
ld ix, (hl)
```

That's a very rough sketch, but to emulate the behaviour from above, you could save however far through the list we searched, then increment hl and do the search again, but comparing the result to that result we saved to make sure it didn't go any further.  If we aren't running in RAM and I can't place a sentinel, then I could instead load bc with the length of the list and throw in a nz check. I think that might be preferable regardless, since if I can compact it small enough I can use .db for list2, and have relative jumps saved instead, but that stuff isn't too important at this point. 
I feel I may be missing something, since the current expr.asm seems more complex than it needs to be, but if I could successfully implement this idea I think it could save as many as 100 bytes, not to mention being easier to read and understand, and extend if necessary Any thoughts?

**Comment by hsoft** [comment]
On @schierlm's suggestion, I changed this algo from "divide and conquer" to "recursive descent" (I don't remember where that suggestion took place...) so that parens support would be easier to implement (it isn't implemented yet).

It *did* result in the complexification of the code, but it will greatly simplify a correct interpretation of parens. The algo is roughly a transation of https://github.com/hsoft/moneyguru/blob/master/ccore/amount.c#L465 which itself is inspired from https://stackoverflow.com/a/9329509 .

From what I understand of your proposal, it does look like "divide and conquer". It is simpler, yes, but (according to @schierlm), makes handling of some edge cases as well as handling of parens much more complex.

**Comment by Clanmaster21** [comment]
That makes sense, I was just thinking and to implement parentheses in my method I'd probably count ")" as an end of expression character, and upon finding "(" make a call to parseExpr or something like that, I'm unsure it'd be as elegant though. I might give it a go just for practice anyway. I was mostly trying to find a way to avoid doing so many comparisons and loads into ix, it's really annoying when you have to do a bunch of comparisons but not quite enough that it's worth bypassing them somehow.

**Comment by hsoft** [comment]
I'll let @schierlm correct me, but from what I understood from his comments, he was saying "I've been down that road, trust me, you want to go with recursive descent". I trusted him :)

**Comment by Clanmaster21** [comment]
Fair enough

**Comment by schierlm** [comment]
The original discussion about the parser started here: https://github.com/hsoft/collapseos/commit/704d32279aeb0c8d1790ced4e5e721bfa741542a#r36103087

Background was that the old implementation got operator precedence wrong in many cases (e.g. `10-3-1` should be 6, but was 8 as it was calculated`10-(3-1)`).

My point was that it is possible to get divide&conquer to parse precedence right, but the code is much more complex than doing recursive descent. Especially when parentheses are involved, but even without parentheses, if you have an expression like `a*b-c*d-e*f/g`, the correct point to divide first ist the **second** `-`.

With recursive descent, you have your parser in multiple layers. The lowest layer can only parse atomic values like `123` or prefix expressions like `-123`. This is implemented when you call `parseNumber`. The next layer will be able to add the highest precedence operators, here bit shifts, so `12}2` can be parsed. The next layer will add the next operators, e.g. `<something>*<something>`, while using the bitshift layer to parse the `<something>`s. The same way, next layer adds addition and subtraction. Due to the way this is constructed, multiplication and division will be done in higher precedence than addition and subtraction. Bit shifts even higher precedence, and unary operators like `-` have highest precedence. Parentheses need equally high precedence as unary `-`, so they will eventually get added to `parseNumber`. Pseudocode:

```
if (number starts with -)
   skip over -, and parse the rest as a number, negate the result
elseif (number starts with "(")
  skip over "(", parse the rest a complete new expression (not just a number), validate that the character after the expression is a ")", skip over the ")", return the value of the expression
else
call EXPR_PARSE
endif
```

To answer your question, parsing `10+ * 10` should result in an error (I did not test it),

Upper layer will parse it as `<something> + <something>`, the first <something> parses fine, but the second `<something>` cannot be parsed, as it starts with a unary `*`, but there is no code for unary `*`. The code for binary `*` cannot be reached as it requires some kind of number first.

On the other hand `10*-10`  (-100) or even `10--10` (20) should parse fine, as the unary minus is parsed if there is no first operand (and as binary minus if there is).

**Comment by Clanmaster21** [comment]
Thanks for the explanation, I get it now. I was thinking that since `_parseAddSubs` called  `_parseMultDiv` then after an addition it'd then expect a multiplier, but I ignored that `_parseMultDiv` then calls the next layer down, so it'd get to `_parseNumber` and error out.  I've been trying out a few ideas and looking at it I do agree that recursive descent is a much cleaner solution than my ideas. I ended up with something similar to the [shunting-yard algorithm](https://en.wikipedia.org/wiki/Shunting-yard_algorithm) except it processed the resulting stacks to get a value rather than to get an RPN expression. What I'm looking at now is editing the recursive descent algorithm so that `_parseAddSubst` and `_parseMultDiv` etc. are identical, and can all be handled as a single function. I don't think it'll actually be an improvement, however I'll at least be satisfied that I got rid of all those sequential tests and loads, so I'll put it here and then close the issue when I'm done with it.

**Comment by schierlm** [comment]
I think I know what algorithm you were after. :smile:
That algorithm is useful if you have configurable operators and precedence (for recursive descent, the operator depth is more or less fixed), or if you want to build an interactive infix calculator (as it can easily resume the calculation when you enter the next operator, and the top of the operand stack is always the value you want to see on the display), but in general it is both slower and more memory consuming than recursive descent, so I think for this project recursive descent fits better.

**Comment by Clanmaster21** [comment]
I've gone and done some more research, and ended up coming across [Precedence Climbing](https://en.wikipedia.org/wiki/Operator-precedence_parser), which I think could be an improvement to recursive descent, as its runtime doesn't scale with the existing number of precedence levels, and also I can reorder the operand search arbitrarily to put the more common operands first. I've written some rough code, I haven't tested it yet so I'm sure it doesn't work but I'll post it for now anyway. I haven't analysed the efficiency or stack usage of my implementation yet, but once I'm done fixing, testing and optimising it I think it could be worth considering.
```
; uses hl' and de' as the left hand side (lhs) and right hand side (rhs)
; requires minor tweaks to _parseNumber and the .ops functions
ParseExpr:
	ld 	b, 1		; b is minimum precedence
	call 	_parseNumber	; DE' is lhs
	exx \ ex hl, de \ exx
	call	ParseExpr1
	ret

ParseExpr1:	; min precedence in b, lhs of op in hl'
	ld	a, (hl)
	call	.precedence	; converts a to its precedence, and place the corresponding operation in ix
	ret	nz
.while1:
	cp	b
	jr	c, .break1	; break if precedence of the operator is below the minimum
	ld	c, a 
	inc	c 		; c is p(op)+1 (makes comparisons easier later)
	inc	hl
	call	_parseNumber	; DE' is rhs, a is next operator and hl is advanced.
	ret	nz


	push	ix	; save operation
	exx
	push	hl	; save lhs
	exx

.while2:
	call	.precedence
	ret	nz
	cp	c
	jr	nc, .break2	; break if p(lookahead) > p(op)

	push	bc		; save min_precedence and p(op)
	ld	b, a
	call	ParseExpr1	; sets DE' to result
	ret	nz
	; a isn't protected, should be the precedence of the next op
	pop	bc
	ld 	a, (hl)
	jr	.while2

.break2:
	pop	ix
	exx
	pop	hl
	ex	af, af'		; let af' be destroyed in callIX
	call	callIX
	ex	af, af'
	; Change these functions so HL' is the result
	exx
	jr	.while1
	
.break1:
	exx
	ex	hl, de
	exx
	ret ; returns result in DE', the rhs
	

; place operation in ix, and precedence in something
.precedence:
	push	bc
	push	hl
	ld	bc, 11		; length of operand list
	ld	hl, .list
	cpir
	ret	nz		; error, operand not found
	rl	c 		; bc is now 22 - 2*operator's position
	add	hl, bc		; hl is now .list + 11 - operator's position
	ld	a, (hl)
	ld	hl, .ops
	add	hl, bc		; hl is now .ops + 22 - 2*operator's position
	ld	c, (hl)		; bc no longer needed, load address into it
	inc	hl
	ld	b, (hl)
	push	bc 		; put address into ix
	pop	ix
	pop	hl
	pop 	bc
	ret

.list:
db 0x00,"+-*/%&", 0x7c, "^}{"	; chosen so that more common operations are first.
db 3,3,3,3,3,2,2,2,1,1,0	; list of precendences, backwards
.ops:			; list of operations, also backwards
dw .add, .minus, .mult, .div, .mod, .and, .or, .xor, .rshift, .lshift
; if op is null, it loads the two bytes before .add, but it won't be executed
```

**Comment by Clanmaster21** [comment]
It seems the project is shifting towards Forth, would it be more useful if I try a Forth implementation of this?

**Comment by hsoft** [comment]
I'm not sure what the purpose of a expression parser would be in the Forth context. I'm not planning on re-implementing a BASIC in Forth and the assembler is using Forth as an interpreter.

**Comment by Clanmaster21** [comment]
Fair enough
