### ISSUE TITLE
Suggested Collapse OS release nicknames: covid, plague, smallpox, etc.

### ISSUE THREAD

**Issue by pfalcon** [hsoft/collapseos#91]
> I expect our global supply chain to collapse ...

Is this (stuff do jour) how you [expected](https://collapseos.org/why.html) Collapse OS to come to relevance?

Anyway, the suggestion is to nickname the releases based on viruses and bacteria, starting, of course, with COVID. Should extend the overall "collapse" theme and help with https://github.com/hsoft/collapseos/issues/89.

**Comment by hsoft** [comment]
Closing in reference to https://github.com/hsoft/collapseos/blob/master/CONTRIBUTING.md#serious

I'm not sure that covid is quite it yet. If it was, Collapse OS wouldn't be ready and would be of little use.

It could be it, but if I had to bet, I'd bet it would greatly weaken our global supply chain, without making it collapse entirely. We'll desperately try to keep it afloat, but we'll fail because of peak oil and cultural bankruptcy. Then another event will come along and be the *coup de grace*.
